# Generated by Django 2.2.6 on 2019-10-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_auto_20191022_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(choices=[('Programación', 'Programación'), ('Diseño', 'Diseño'), ('Marketing', 'Marketing'), ('Finanzas', 'Finanzas'), ('Emprendimiento', 'Emprendimiento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.CharField(choices=[('Estudiante', 'Estudiante'), ('Profesional', 'Profesional')], max_length=30),
        ),
    ]
